version: '3.9'

services:
  host_postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_postgres
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 1s
      retries: 2

  host_mysql:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 2s
      retries: 2

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      host_postgres:
        condition: service_healthy
      host_mysql:
        condition: service_healthy
    volumes:
      - ./ETL_script.py:/app/ETL_script.py  
    command: ["python", "/app/ETL_script.py"]
    environment:
      POSTGRES_HOST: host_postgres
      POSTGRES_DB: db_postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      MYSQL_HOST: host_mysql
      MYSQL_DB: db_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
