version: '3.9'

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 2

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ETL_script.py:/app/ETL_script.py  
    command: ["python", "/app/ETL_script.py"]
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: test_db 
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    restart: "no"
    
